services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DD_SERVICE=sun-test-service1
      - DD_ENV=stg
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=dd-agent
      - DD_TRACE_AGENT_PORT=8126
    links:
      - dd-agent:dd-agent
    depends_on:
      - dd-agent
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "3002:3002"
    environment:
      - DD_SERVICE=sun-test-service1
      - DD_ENV=stg
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=dd-agent
      - DD_TRACE_AGENT_PORT=8126
      - PORT=3002
    links:
      - dd-agent:dd-agent
    depends_on:
      - dd-agent
      - redis


  dd-agent:
    image: datadog/agent
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126/tcp"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
